# Generated by Django 5.1.5 on 2025-02-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
