# Generated by Django 5.1.5 on 2025-02-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
