# Generated by Django 5.1.5 on 2025-02-06 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_participant_rsvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='rsvp_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RSVP',
        ),
    ]
